package View;


import Controller.ClientController;
import Model.Client;
import Model.Fly;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.HashMap;

public class GameMainFrame extends javax.swing.JFrame {

    protected Point position;
    private int[] currentSize;
    private ClientController clientController;
    public Client client;

    /**
     * Creates new form GameFrameClient
     */
    public GameMainFrame(ClientController cc, Client c) {
        initComponents();
        currentSize = new int[]{jPanel1.getWidth(), jPanel1.getHeight()};
        this.clientController = cc;
        this.client = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        this.setTitle("GameHuntFly");
        jPanel1 = new javax.swing.JPanel();
        //flyImage = new Fly();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory
                .createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentResized(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("All Players Score");

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList1);

        jLabel2.setText("UserName: ");

        userNameLabel.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
                jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout
                .setHorizontalGroup(jPanel2Layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jPanel2Layout
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                jPanel2Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(
                                                                jScrollPane2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                0,
                                                                Short.MAX_VALUE)
                                                        .addComponent(
                                                                logoutButton,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                        .addGroup(
                                                                jPanel2Layout
                                                                        .createSequentialGroup()
                                                                        .addComponent(
                                                                                jLabel2)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(
                                                                                userNameLabel)
                                                                        .addGap(0,
                                                                                0,
                                                                                Short.MAX_VALUE))
                                                        .addGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel2Layout
                                                                        .createSequentialGroup()
                                                                        .addGap(0,
                                                                                24,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(
                                                                                jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                151,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap()));
        jPanel2Layout
                .setVerticalGroup(jPanel2Layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jPanel2Layout
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                jPanel2Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(
                                                                userNameLabel))
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(
                                                jScrollPane2,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                278,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(logoutButton)
                                        .addContainerGap(124, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
                getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
        layout.setVerticalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE).addContainerGap())
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE).addGap(18, 18, 18)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_jPanel1MouseClicked

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_logoutButtonActionPerformed

    private void flyImageMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_flyImageMouseClicked
        // TODO add your handling code here:

    }// GEN-LAST:event_flyImageMouseClicked

    private void jPanel1ComponentResized(java.awt.event.ComponentEvent evt) {// GEN-FIRST:event_jPanel1ComponentResized
        // TODO add your handling code here:
        if (clientController.client.currentPoint != null) {
            for (Fly flyImage : client.allFlies) {
                flyImage
                        .setLocation(
                                (int) (this.jPanel1.getWidth() * flyImage.x - flyImage
                                        .getWidth() / 2),
                                (int) (this.jPanel1.getHeight() * flyImage.y)
                                        - flyImage.getHeight() / 2);
                flyImage.repaint();
            }
        }
    }// GEN-LAST:event_jPanel1ComponentResized

    private void formWindowClosing(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosing
        this.clientController.logout();
    }// GEN-LAST:event_formWindowClosing

    public void updatePlayersPanel(HashMap playersMap) {


        int size = playersMap.size();
        String[] players = new String[size];
        playersMap.keySet().toArray(players);
        DefaultListModel<String> model = new DefaultListModel<String>();
        String tempPlayer;
        for (int i = 0; i < size; i++) {
            for (int j = i + 1; j < size; j++) {
                if ((Integer) (playersMap.get(players[i])) < (Integer) (playersMap
                        .get(players[j]))) {
                    tempPlayer = players[j];
                    players[j] = players[i];
                    players[i] = tempPlayer;
                }

            }
        }
        for (String name : players) {
            model.addElement(name + " - " + playersMap.get(name));
        }
        this.jList1.setModel(model);
    }

    public int getWidthGamePanel() {
        return this.jPanel1.getWidth();
    }

    public int getHightGamePanel() {
        return this.jPanel1.getHeight();
    }

    public JPanel getPanel1() {
        return this.jPanel1;

    }

    public void addFly(ArrayList<Fly> flyList) {
        for (Fly flyImage : flyList) {
            flyImage.setSize(50, 50);
            //  System.out.println(flyImage.x + "-" + flyImage.y);
            flyImage
                    .setLocation(
                            (int) (this.jPanel1.getWidth() * flyImage.x - flyImage
                                    .getWidth() / 2),
                            (int) (this.jPanel1.getHeight() * flyImage.y)
                                    - flyImage.getHeight() / 2);
          /*  System.out.println(jPanel1.getWidth() + "-" + flyImage
                    .getWidth() + flyImage.location());*/
            jPanel1.setLayout(null);

            jPanel1.add(flyImage);
            jPanel1.validate();
            flyImage.repaint();
        }
    }

    public void removeAllFly() {
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
                jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        for (Fly flyImage : client.allFlies) {
            jPanel1Layout.removeLayoutComponent(flyImage);
        }
    }

    @Override
    public void paint(Graphics arg0) {
        // TODO Auto-generated method stub
        super.paint(arg0);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton logoutButton;
    public javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
